openapi: 3.0.0
info:
  title: LinkPlay HTTP API
  description: My API description
  version: 1.0.0
servers:
  - url: http://localhost:3000/proxy
    description: WiiM device
paths:
  /httpapi.asp?command=getStatusEx:
    get:
      summary: Root endpoint
      description: Returns 'Hello, World!'
      responses:
        "200":
          description: Successful response
          content:
            text/html:
              schema:
                type: object
                properties:
                  message:
                    type: string
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
