openapi: 3.0.0
info:
  title: Linkplay/WiiM HTTP API
  description: >-
    HTTP API for Linkplay/WiiM devices.


    You can send 'HTTPs Get' request to the device, most of the response is in
    the JSON format.


    Request format is https://x.x.x.x/httpapi.asp?command=********

    x.x.x.x is the IP address of the device (Below, we assume the IP of the
    device is 10.10.10.254) ******* is the actual command.


    Commands can contain both integers and strings, denoted as '%d' for integers
    and '%s' for strings, respectively.


    This Swagger doc uses a reverse proxy to access the device. See the
    description for the actual command.
  version: 1.2.0
  contact: {}
servers:
  - url: 'http://localhost:3000/proxy'
    description: Reverse proxy to access the device. See the README for more information.
tags:
  - name: Device information
    description: Get the device information
  - name: Network
    description: Get the network status
  - name: Playback control
    description: Get and set playback controls
  - name: EQ
    description: Get and set equalizer settings
  - name: Device control
    description: Control the device
  - name: Alarm clock
    description: Get and set alarm clock
  - name: Source Input Switch
    description: Switch between inputs
  - name: Presets
    description: Manage presets
  - name: Track Metadata
    description: Get Current Track Metadata
  - name: Audio Output Control
    description: Get and set audio output mode
paths:
  /getStatusEx:
    get:
      tags:
        - Device information
      summary: Get device information
      description: 'Makes a call to https://10.10.10.254/httpapi.asp?command=getStatusEx'
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      responses:
        '200':
          description: Successful response
          content:
            text/html:
              schema:
                type: object
                properties:
                  language:
                    type: string
                  ssid:
                    type: string
                    description: Name of the device
                  ...:
                    type: string
      parameters: []
  /wlanGetConnectState:
    get:
      tags:
        - Network
      summary: Get the connection status
      description: >+
        Makes a call to
        https://10.10.10.254/httpapi.asp?command=wlanGetConnectState


        Note the return result is not in json.


        Return string:

        Return string Description

        PROCESS In progress

        PAIRFAIL Wrong password

        FAIL Connect fail

        OK connected

      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      responses:
        '200':
          description: Successful response
          content:
            text/html:
              schema:
                type: string
              examples:
                PROCESS:
                  summary: In progress
                  value: PROCESS
                PAIRFAIL:
                  summary: Wrong password
                  value: PAIRFAIL
                FAIL:
                  summary: Connect fail
                  value: FAIL
                OK:
                  summary: Connected
                  value: OK
      parameters: []
  /getPlayerStatus:
    get:
      tags:
        - Playback control
      summary: Get the playback status
      description: 'Makes a call to https://10.10.10.254/httpapi.asp?command=getPlayerStatus'
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      responses:
        '200':
          description: Successful response
          content:
            text/html:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: Playback status
                    enum:
                      - PLAYING
                      - PAUSE
                      - STOP
                      - BUFFERING
                  ...:
                    type: string
      parameters: []
  '/setPlayerCmd:hex_playlist:url:{index}':
    get:
      summary: ''
      description: >
        http://10.10.10.254/httpapi.asp?command=setPlayerCmd:hex_playlist:url:<index>

        Play the URl (URI is the m3u or ASX playlist link, index is the start
        index), here, url should be

        hexed (please refer to 1.3)
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters:
        - name: index
          in: path
          required: true
          schema:
            type: string
      responses:
        default:
          description: Default response
      tags:
        - Playback control
      deprecated: true
  '/setPlayerCmd:pause':
    get:
      summary: Pause
      description: 'https://10.10.10.254/httpapi.asp?command=setPlayerCmd:pause'
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters: []
      responses:
        default:
          description: Default response
      tags:
        - Playback control
  '/setPlayerCmd:resume':
    get:
      summary: Resume
      description: 'https://10.10.10.254/httpapi.asp?command=setPlayerCmd:resume'
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters: []
      responses:
        default:
          description: Default response
      tags:
        - Playback control
  '/setPlayerCmd:onepause':
    get:
      summary: Toggle pause/play
      description: |-
        https://10.10.10.254/httpapi.asp?command=setPlayerCmd:onepause
        If the state is paused, resume it; otherwise, pause it.
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters: []
      responses:
        default:
          description: Default response
      tags:
        - Playback control
  '/setPlayerCmd:prev':
    get:
      summary: Previous
      description: 'https://10.10.10.254/httpapi.asp?command=setPlayerCmd:prev'
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters: []
      responses:
        default:
          description: Default response
      tags:
        - Playback control
  '/setPlayerCmd:next':
    get:
      summary: Next
      description: 'https://10.10.10.254/httpapi.asp?command=setPlayerCmd:next'
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters: []
      responses:
        default:
          description: Default response
      tags:
        - Playback control
  '/setPlayerCmd:seek:position':
    get:
      summary: Seek
      description: |-
        https://10.10.10.254/httpapi.asp?command=setPlayerCmd:seek:position
        Position is from 0 to duration in second.
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters: []
      responses:
        default:
          description: Default response
      tags:
        - Playback control
  '/setPlayerCmd:stop':
    get:
      summary: Stop
      description: 'https://10.10.10.254/httpapi.asp?command=setPlayerCmd:stop'
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters: []
      responses:
        default:
          description: Default response
      tags:
        - Playback control
  '/setPlayerCmd:vol:{value}':
    get:
      summary: Set volume
      description: |-
        https://10.10.10.254/httpapi.asp?command=setPlayerCmd:vol:value
        Value can be 0 to 100.
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters:
        - name: value
          in: path
          required: true
          schema:
            type: integer
          description: Value can be 0 to 100.
      responses:
        default:
          description: Default response
      tags:
        - Playback control
  '/setPlayerCmd:mute:{n}':
    get:
      summary: Mute
      description: >-
        https://10.10.10.254/httpapi.asp?command=setPlayerCmd:mute:n

        Mute: n=1

        Unmute: n=0

        The slave mute state will be set at the same time when it's in group
        play.
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters:
        - name: 'n'
          in: path
          required: true
          schema:
            type: string
            enum:
              - '1'
              - '0'
            default: '1'
          description: |-
            Mute: n=1
            Unmute: n=0
      responses:
        default:
          description: Default response
      tags:
        - Playback control
  '/setPlayerCmd:loopmode:{n}':
    get:
      summary: Loop mode set
      description: |
        https://10.10.10.254/httpapi.asp?command=setPlayerCmd:loopmode:n

        n = 
        0 - Sequence, no loop
        1 - Single loop
        2 - Shuffle loop
        -1 - Sequence loop
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters:
        - name: 'n'
          in: path
          required: true
          schema:
            type: string
            enum:
              - '0'
              - '1'
              - '2'
              - '-1'
          description: |-
            0 Sequence, no loop
            1 Single loop
            2 Shuffle loop
            -1 Sequence loop
      responses:
        default:
          description: Default response
      tags:
        - Playback control
  /getNewAudioOutputHardwareMode:
    get:
      summary: Get audio output mode
      description: |-
        JSON Response：
        {"hardware":"2","source":"0","audiocast":"0"}
        Description：
        Field Description
        hardware Hardware Interface output mode:
        1: AUDIO_OUTPUT_SPDIF_MODE
        2: AUDIO_OUTPUT_AUX_MODE
        3: AUDIO_OUTPUT_COAX_MODE
        source BT source output mode:
        0: disable
        1: active
        audiocast Audio cast output mode:
        0: disable
        1: active
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters: []
      responses:
        default:
          description: Default response
      tags:
        - Audio Output Control
  '/setAudioOutputHardwareMode:{n}':
    get:
      summary: Set audio output mode
      description: |-
        Field Description
        Hardware Interface output mode:
        1: AUDIO_OUTPUT_SPDIF_MODE
        2: AUDIO_OUTPUT_AUX_MODE
        3: AUDIO_OUTPUT_COAX_MODE
        Response is 'OK'
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters:
        - name: 'n'
          in: path
          required: true
          schema:
            type: string
            enum:
              - '1'
              - '2'
              - '3'
          description: |-
            Hardware Interface output mode:
            1: AUDIO_OUTPUT_SPDIF_MODE
            2: AUDIO_OUTPUT_AUX_MODE
            3: AUDIO_OUTPUT_COAX_MODE
      responses:
        default:
          description: Default response
      tags:
        - Audio Output Control
  /getMetaInfo:
    get:
      summary: Get Current Track Metadata
      description: |-
        JSON Response
        {
         "metaData": {
         "album": "Country Heat",
         "title": "Old Dirt Roads",
         "artist": "Owen Riegling",
         "albumArtURI ": "https://m.media-amazon.com/images/I/51iU0odzJwL.jpg",
         "sampleRate ": "44100",
         "bitDepth": "16"
         }
        }
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters: []
      responses:
        default:
          description: Default response
      tags:
        - Track Metadata
  '/setPlayerCmd:play:{url}':
    get:
      summary: Play audio URL
      description: |-
        https://10.10.10.254/httpapi.asp?command=setPlayerCmd:play:url
        Play the URL. URL points to an audio stream address.
        Response is always 'OK' now
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters:
        - name: url
          in: path
          required: true
          schema:
            type: string
            default: >-
              http://as-hls-ww-live.akamaized.net/pool_01505109/live/ww/bbc_radio_one/bbc_radio_one.isml/bbc_radio_one-audio%3d96000.norewind.m3u8
          description: URL points to an audio stream address
      responses:
        default:
          description: Default response
      tags:
        - Playback control
  '/setPlayerCmd:playlist:{url}:{index}':
    get:
      summary: Play audio playlist
      description: >-
        https://10.10.10.254/httpapi.asp?command=setPlayerCmd:playlist:url:<index>

        Play the playlist with the URL (URL points to the m3u or ASX playlist
        link, index is the start

        index).

        Response is always 'OK' now.
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters:
        - name: index
          in: path
          required: true
          schema:
            type: string
        - name: url
          in: path
          required: true
          schema:
            type: string
            default: >-
              https://gist.githubusercontent.com/bpsib/67089b959e4fa898af69fea59ad74bc3/raw/685789e28187c0a15da978b51d436a140d5ea207/BBC-Radio-HLS.m3u
      responses:
        default:
          description: Default response
      tags:
        - Playback control
  /EQOn:
    get:
      summary: Turn on the EQ
      description: |-
        https://10.10.10.254/httpapi.asp?command=EQOn

        JSON Response:
        {"status":"OK"} or {"status":"Failed"}
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters: []
      responses:
        '200':
          description: Default response
          content:
            text/html:
              schema: {}
      tags:
        - EQ
  /EQOff:
    get:
      summary: Turn off the EQ setting
      description: |
        https://10.10.10.254/httpapi.asp?command=EQOff

        JSON Response:
        {"status":"OK"} or {"status":"Failed"}
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters: []
      responses:
        '200':
          description: Default response
          content:
            text/html:
              schema: {}
      tags:
        - EQ
  /EQGetStat:
    get:
      summary: Check if the EQ is ON or OFF
      description: |-
        http://10.10.10.254/httpapi.asp?command=EQGetStat

        JSON Response:
        {"EQStat":"On"} or {"EQStat":"Off"}
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters: []
      responses:
        '222':
          description: Default response
          content:
            text/html:
              schema: {}
      tags:
        - EQ
  /EQGetList:
    get:
      summary: Check all the possible EQ settings
      description: >
        http://10.10.10.254/httpapi.asp?command=EQGetList


        Response:

        ["Flat", "Acoustic", "Bass Booster", "Bass Reducer", "Classical",
        "Dance", "Deep", "Electronic",

        "Hip-Hop", "Jazz", "Latin", "Loudness", "Lounge", "Piano", "Pop", "R&B",
        "Rock", "Small

        Speakers", "Spoken Word", "Treble Booster", "Treble Reducer", "Vocal
        Booster"]
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters: []
      responses:
        '200':
          description: Default response
          content:
            text/html:
              schema: {}
      tags:
        - EQ
  '/EQLoad:{name}':
    get:
      summary: Set the specific EQ with name
      description: >-
        http://10.10.10.254/httpapi.asp?command=EQLoad:xxx


        JSON Response:

        {"status":"OK"} or {"status":"Failed"}


        Note: xxx is the one of the name in the list returned by EQGetList,
        i.e., EQLoad:Flat
      externalDocs:
        description: HTTP API for WiiM PRODUCTS Version 1.2
        url: 'https://www.wiimhome.com/pdf/HTTP%20API%20for%20WiiM%20Products.pdf'
      parameters:
        - name: name
          in: path
          required: true
          schema:
            type: string
            enum:
              - Flat
              - Acoustic
              - Bass Booster
              - Bass Reducer
              - Classical
              - Dance
              - Deep
              - Electronic
              - Hip-Hop
              - Jazz
              - Latin
              - Loudness
              - Lounge
              - Piano
              - Pop
              - R&B
              - Rock
              - Small Speakers
              - Spoken Word
              - Treble Booster
              - Treble Reducer
              - Vocal Booster
          description: 'The name in the list returned by EQGetList, i.e., EQLoad:Flat'
      operationId: ''
      responses:
        '200':
          description: Default response
          content:
            text/html:
              schema: {}
      tags:
        - EQ
security: []
components:
  links: {}
  callbacks: {}
  schemas: {}
  securitySchemes: {}
externalDocs:
  url: 'https://github.com/cvdlinden/wiim-httpapi'
